language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t swarthofole/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true swarthofole/docker-react npm run test

deploy:
        provider: elasticbeanstalk
        region: "eu-west-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-eu-west-1-178476848778"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: "$AWS_SECRET_KEY"
